<div class="modal-header" id='modal-header'>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="modal-title">Delete Record</h4>
</div>

<div class="modal-body" id='modal-body'>
    <label class="col-sm-12 control-label">Are you sure to delete this record ?</label>
    <br/>
</div>

<div class="modal-footer" id='modal-footer'>
    <button type="button" class="btn btn-default" data-dismiss="modal"><?= $this->translate("No")?></button>
    <button type="button" class="btn btn-primary" id='modal-submit' href="{{action('CredentialsController@delete',$credential->id)}}<?= $this->translate("Yes")?></button>
</div>